### ISSUE TITLE
Реализовать поощрение

### ISSUE THREAD

**Issue by AlexanderNest** [EvgeniyLizogubov/public-voting#5]
Поощрение:
раз в n дней проверка на поощрение
отправка на почту сертификата в формате pdf (или другом, если он подходит больше)
пользователь сам может в приложении запросить сертификат, а мы покажем ему страничку с этим сертификатом

**Comment by EvgeniyLizogubov** [comment]
Done

**Comment by EvgeniyLizogubov** [comment]
Done
